### ISSUE TITLE
Animate.css

### ISSUE THREAD

**Issue by barkingPete** [silexlabs/Silex#146] opened 2014-06-19 21:58 UTC
I have (finally) follwed the instructions in #87 and I have been using the animated.css functions. I pasted the text "animated flip" into the CSS classes box (Apollo mode) and was able to see the animations in action. I note that almost any object can be animated and animations can be applied to images and to containers and result can be very dynamic. 

However I note that on publication the animations are best (or even only) seen in Chrome and "first time only" for firefox and not at all for internet exploder, A great set of effects but not not widely usable in this version. It would be nice if the major browsers worked (mostly) uniformly.

**Comment by singchan** [comment] 2016-08-17 14:50
duplicate of this feature request
https://github.com/silexlabs/Silex/issues/84

**Closed by singchan** 2016-08-17 14:50 UTC
Labels: question, sticky
