### ISSUE TITLE
Bug new version : resizing elements with border

### ISSUE THREAD

**Issue by antosilex** [silexlabs/Silex#500] opened 2016-10-15 19:23 UTC
When i try to resize elements (text box or container) with border, with the mouse it's impossible to resize as you want, the element reduce itslef 
It works fine when i enter the numbers in the position and size box in the properties
When i delete the border everything works fine

I have the same bug on preprod

**Comment by lexoyo** [comment] 2016-10-15 20:52
Reproduced, thank you
I'll let you know when it is fixed

**Comment by lexoyo** [comment] 2016-10-16 12:15
this shloud be fixed on preprod, can you confirm please? (and test and look for side effects ;) )
thx @antosilex !

**Comment by antosilex** [comment] 2016-10-17 06:18
it's better but there is still a bug on preprod when i try to reduce the element using the top right corner it moves

**Comment by lexoyo** [comment] 2016-10-17 08:29
this is because the text box can not be smaller than its content
i close the issue then thx

**Closed by lexoyo** 2016-10-17 08:29 UTC
Labels: bug, help wanted
