### ISSUE TITLE
With click on the element the editor don't change

### ISSUE THREAD

**Issue by Lunamond42** [silexlabs/Silex#543] opened 2017-01-29 07:20 UTC
Hi.
I'm using new Silex. I have a problem. On the beginning, all working perfect. But now, when I click on a picture, text and so on, the editor on the right site is not changing. So I can't work in the CSS, set a Link, nothing. The only element details that Silex me show is from the background.
Can you help me?
Thank you.
Best regards,
Luna
![issue silex](https://cloud.githubusercontent.com/assets/25409457/22402560/cb5220a2-e5fb-11e6-8053-f2ccfb57d1ff.png)

**Comment by lexoyo** [comment] 2017-01-29 12:06
Hi Luna!
Did you try reloading Silex completely and then open your site again?

**Comment by Lunamond42** [comment] 2017-01-29 19:48
Yes, I did. But nothing changed. Sometimes the file didn't open. I started today the project new. All is working. May be a problem with the saving process?

**Comment by lexoyo** [comment] 2017-01-29 21:17
Very unlikely
What is your os? What browser and cloud service do you use?
Do you copy paste directly from github to silex?


On Jan 29, 2017 20:48, "Lunamond42" <notifications@github.com> wrote:

Yes, I did. But nothing changed. Sometimes the file didn't open. I started
today the project new. All is working. May be a problem with the saving
process?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/silexlabs/Silex/issues/543#issuecomment-275940638>, or mute
the thread

**Comment by lexoyo** [comment] 2017-02-05 14:37
is it working?

**Comment by tradosevic** [comment] 2017-08-22 07:47
Can reproduce the issue, almost exactly:
- in the beginning, worked perfecty
- now works after hard refresh / browser restart *
- Kubuntu 17.04, Chromium 60, Firefox 55
- although the values in the editor do not change, when you enter new values, they get applied (but not consistently)
- *- looks like it happens after you select a specific element with a custom css class and relative positioning (although some other simmilar elements do not invoke the bug, again, not consistent)

**Comment by lexoyo** [comment] 2017-08-22 09:14
Nice! I reproduce it now, thx

It seems to be resolved in the next version of silex already
http://preprod.silex.me/

Can you confirm?

**Comment by tradosevic** [comment] 2017-08-22 09:35
I can confirm - the issue does not occur, whatever I do with the divs that were problematic before.
Thanks! _(offt: Great project in general, two thumbs up!)_

**Comment by lexoyo** [comment] 2017-08-22 09:52
Ok interesting
You can use this version on preprod then, and switch back to editor.silex.me in a month or two when it is live (stay tuned here to be notified when I release the new version)
Thx for the thumbs up! :)

**Closed by lexoyo** 2017-08-22 09:52 UTC
Labels: bug
