### ISSUE TITLE
difficulty loading project file

### ISSUE THREAD

**Issue by parkadia** [silexlabs/Silex#613] opened 2017-06-03 15:23 UTC
In the last few days, I have had difficulty loading my html file for editing. Now, I cannot open it at all. I can load the editor and select the file from the dashboard. But then the editor just waits and waits. I see the message "waiting for editor.silex.me" in the bottom left corner. Any help appreciated.

**Comment by lexoyo** [comment] 2017-06-03 18:53
Hello,
I can not reproduce that, can you share you website with me? (With the assets and everything)

* Which cloud do you use? (Dropbox, github, ftp..)
* What is your OS? If it is Linux there is the offline version of silex you can try (early beta)
* What browser do you use?

**Comment by parkadia** [comment] 2017-06-03 21:19
I have shared the folder parkadia2 in my dropbox (html and assets) with you.
Dropbox is my cloud. OS is Windows 10. Browser is Chrome.
I still cannot load the parkadia2.html.

**Comment by IOU4something** [comment] 2017-06-03 23:44
Im having the same exact issue

**Comment by lexoyo** [comment] 2017-06-04 09:04
Hello

Yes there was an update recently
https://github.com/silexlabs/Silex/issues/591

I can not reproduce this issue, please share a website with me

**Comment by parkadia** [comment] 2017-06-04 11:04
How would you like me to share my website? It is on dropbox and I need an email address. How would you like me to proceed?

**Comment by parkadia** [comment] 2017-06-04 11:26
I have managed to load the website today and make minor text changes. However, I could not import an image and I could not preview the website. I got the following error:

"Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /api/1.0/dropbox/exec/get/parkadia2/parkadia2.html.

Reason: Error reading from remote server"

**Comment by lexoyo** [comment] 2017-06-04 11:54
Thank you @parkadia this may be useful info
For now I have seen nothing which could cause this.. After a while searching I have simply rebooted the server, can you please try again? Who knows...

**Comment by parkadia** [comment] 2017-06-04 14:27
We also rebooted our server and my project loaded. I thought hurray! BUT when I tried to load an image from my dropbox, I got a "loading" message in the centre of the screen and a message bottom left saying "waiting for editor.silex.me". I have now been waiting for 10 minutes.

**Comment by lexoyo** [comment] 2017-06-04 14:35
> We also rebooted our server 

You are not using editor.silex.me?

**Comment by barkingPete** [comment] 2017-06-04 14:53
Hello @lexoyo!
@parkadia was using the standard Silex web editor when these reports were made. When you rebooted the Silex server we took the chance to reboot our firewalls and routers and any relevant computers. That was what @parkadia was referring to.
The issue may be due to something like network latency - the https signals are perhaps "timing out". The problem is usually noticed at some stage of accessing dropbox files. Either by the Silex system when compiling the website - or by the end user trying to access assets top add to the site during normal editing/use.  Sometimes the system starts and runs very well but then "hangs" while waiting for something. Other times it is just slow from the start. We will try to run form several workstations to see if the problem is related to any particular computer setup.

**Comment by lexoyo** [comment] 2017-06-04 15:06
could you try with this server (same but without https)
http://preprod.silex.me/

**Comment by parkadia** [comment] 2017-06-04 15:32
I can load the html file and have managed to load an image from my dropbox. It was very slow but it did happen. So, this probably indicates that htttps is an issue.

However, your preprod silex.me is not the SAME as editor.silex.me. For example,
The page names under 'Links' are not displaying - listed only as {{displayName}}
There is no positional information displaying for elements under 'Styles'
etc. etc.

Therefore, using this version of the editor is not a solution for me as I still cannot effectively work on my project.

**Comment by lexoyo** [comment] 2017-06-04 15:43
> The page names under 'Links' are not displaying - listed only as {{displayName}}

another strange thing
could you please 
* try with firefox
* make a screenshot of this bug for me?

**Comment by lexoyo** [comment] 2017-06-04 15:58
Also, I have setup this server with https and the next version of cloud explorer
https://cloud-explorer2.herokuapp.com/cloud-explorer/cloud-explorer.html

Tell me if you can browse your dropbox with it without experiencing the timeout

**Comment by lexoyo** [comment] 2017-06-04 16:26
Stella,

Even with your website I have no issue editing/adding images or opening files...

This could be a network issue, probably not on your end since @IOU4something has the same issue but anywhere between silex server and you...

The solutions I see
* you wait and try again later... (if it persist I will definitely have to do something anyway, but I don't know what yet)
* we try to make the preprod.silex.me work (it should already)
* we try to setup a server with the next version of cloud explorer (file browser of silex) which is more optimized than the current version but has some issues (which I am willing to fix)
* we setup a silex server on you computer or on a computer in your house, I can help with that, to start there are instructions in Silex readme

Please try this in any case:
* try with firefox
* try to browse your dropbox here: https://cloud-explorer2.herokuapp.com/cloud-explorer/cloud-explorer.html

**Comment by parkadia** [comment] 2017-06-04 16:33
Hiya,

Screen grab attached showing that page names are not displaying on 
preprod.silex.me
Another screen grab shows that class styles and positional information 
for an element are also missing on preprod.silex.me

I will try on firefox if I can find it on another machine but I do not 
want to install it on this computer right now.

Stella

**Comment by parkadia** [comment] 2017-06-04 17:36
Ironically, I too can now edit, open files and add images!!!

The only thing that does not seem to be working correcly is 'Publish'. 
Maybe this is too much to ask, but could you try doing this for me?

For now, I will continue to monitor the performance of 
https://editor.silex.me/ but ultimately I think I need to have it set up 
on my computer. I will discuss this with barkingpete who also joined the 
discussion.

Thank you for your help today. No doubt, I will be in touch again as I 
have a lot, lot more to add to the parkadia website and really want to 
make it work using Silex. Up until these recent issues, I have been very 
impressed with the but wonder if there is a limit to how many pages / 
images / functionality that I can add.

**Comment by parkadia** [comment] 2017-06-04 17:59
I have also shared my published website with you. It would seem that all the assets are there but that the javascript and possibly the css files have not been updated.

**Comment by lexoyo** [comment] 2017-06-04 18:24
Sure I will try to publish tomorrow

Silex has only one server and it is located in France and provided for free by Gandi.net we should ask other national hosting companies to host other instances in other countries... If anyone has time to do that you are welcome to help.

Stella, can you confirm that everything is back to normal on editor.silex.me and I should try to publish on editor.silex.me ?

**Comment by parkadia** [comment] 2017-06-04 18:51
Everything (except for publishing) seems to be back to normal (for now) 
and I can confirm that you should try to publish from editor.silex.me

The project is set up to publish to 'parkadia_published' in my dropbox. 
I have shared this folder with you. Currently, the includes the 
non-working version. Do you want me to delete this?

As for a UK server, I'm not sure I can help but will talk to my 
colleague to see if he has any ideas.

**Comment by parkadia** [comment] 2017-06-05 16:37
I tried loading my project into http://preprod.silex.me/ using firefox. There were the same issues re: Links and Styles as on Chrome.

Did you manage to find time to publish my website?

**Comment by lexoyo** [comment] 2017-06-06 21:42
hello

I took the time to publish your site. It has so many images and pages, this is a first. It took more than 30s to display the publish progress dialog like this:

![screenshot from 2017-06-06 23-21-24](https://user-images.githubusercontent.com/715377/26852664-427c5f94-4b0f-11e7-8767-e367a683020d.png)

And then I left it for a long time and it has published the site...
May be you should try again now? And do not start several publish operations, only one and wait...

![screenshot from 2017-06-06 23-38-04](https://user-images.githubusercontent.com/715377/26853206-5cfb42a2-4b11-11e7-921b-a08ec65d4a81.png)


This is one more sign which shows that publication is not well implemented, I will work on it in the coming months. After the new version of cloud explorer which will make it possible to accelerate the process.

**Comment by parkadia** [comment] 2017-06-06 22:21
I start to publish many time because I cannot determine whether publishing is happening or may computer has hung!

In the process, I have noticed some interesting observations:
1) If I manually copy all the assets to my published directly, the publishing process is quicker. I suspect it looks for files in the published directory

**Comment by parkadia** [comment] 2017-06-07 00:04
Continuing from my previous post (Silex was publishing in the background and failed while I wrote), I appreciate that my website is pushing the editor's publishing abilities to its limits and really hope (BEG) that, over the coming months, you will consider the following:

1) If assets are manually pre-copied to the specified published directory, the publishing process is quicker. I suspect the editor looks for files in the published directory and, if they are not there, copies them to the published directory. But is it necessary to 'download' ALL asset files EACH TIME time the website is published?
2) Currently, all assets are 'downloaded' into one 'assets' sub-directory in the specified published directory. Surely, it would be better to preserve the directory structure of the 'assets' directory used to create/edit the website. Or, at least, this should be an option?
3) It does not seem possible to change the published directory once it has been specified in the system dialogue at the start of a project.
4) If a link (i.e. an image in the dropbox has been accidentally deleted or an external website is no longer available), should this prevent the publishing of the website?
5) The publishing process sometimes fails with an 'unknown error'. If it is restarted, the 'downloading' of files gets out of sequence.
For instance, it starts by 'downloading' file no. 513 and says it has 512 files left to download.
Then, it says it is has 200 files left to 'download' (where 200 was the point at which it previously failed), followed by 199 files.
Then it is says, 511 files , then 510 files.
Then 198 files.
Then 509.
197.
508.
196 etc...
It is as if each asset has a pre-defined ID no. according to the order it was entered into the editor and that the editor's file tree is then split in half (and in half again) each time the publishing process fails and restarts. However, despite these disconcerting onscreen messages, the website does eventually publish!
6) If a 'text element' is linked to a page, and the only text in the 'text element' is also manually linked to the same page, the manually linked text is splattered all over the 'published' screen. Nonetheless, the underlying website functions correctly.

PLEASE, please keep working on publishing because I am committed to making my website work in Silex and, as I have said before, I have lots and lots more content and functionality to add.

**Comment by lexoyo** [comment] 2017-06-09 15:30
> I appreciate that my website is pushing the editor's publishing abilities to its limits and really hope (BEG) that, over the coming months, you will consider the following

I will, and I hope that you will stay tuned and be available for beta testing 

> If assets are manually pre-copied to the specified published directory, the publishing process is quicker. I suspect the editor looks for files in the published directory and, if they are not there, copies them to the published directory. But is it necessary to 'download' ALL asset files EACH TIME time the website is published?

definitely not
this is not trivial since the assets might be updated but there must be a way to cache them

> It does not seem possible to change the published directory once it has been specified in the system dialogue at the start of a project.

Yes this is possible, just open the settings dialog, then "pubish settings" then "configure"

> If a link (i.e. an image in the dropbox has been accidentally deleted or an external website is no longer available), should this prevent the publishing of the website?

Yes I think it should you're right

> The publishing process sometimes fails with an 'unknown error'. If it is restarted, the 'downloading' of files gets out of sequence.

When it gets out of sequence I am pretty sure that it is because you have several publications occuring at the same time. This should not be possible, I will look at it, but in the mean time please do not start several publications at the same time (wait for the dialog, then wait untill it is finished)

> If a 'text element' is linked to a page, and the only text in the 'text element' is also manually linked to the same page, the manually linked text is splattered all over the 'published' screen. Nonetheless, the underlying website functions correctly.

I don't understand, can you please explain or give a screenshot?

Thank you for the feature requests and the bug reports, this is a precious contribution

**Comment by lexoyo** [comment] 2017-06-27 07:30
I close this issue since there is no bug anymore but several features being developped
Feel free to reopen if there is still an issue with the server being unresponsive

**Closed by lexoyo** 2017-06-27 07:30 UTC
Labels: bug
