### ISSUE TITLE
[Mobile] [Hamburger] Hide pages in the hamburger menu?

### ISSUE THREAD

**Issue by Tyrael84** [silexlabs/Silex#650] opened 2017-11-03 16:31 UTC
Is it possible to pick and choose which pages are displayed in the 'hamburger' menu on the mobile version of the site. I would assume it would involve some sort of JS or CSS.

**Comment by lexoyo** [comment] 2017-11-03 17:38
closing this one as it is a duplicate of #651

**Closed by lexoyo** 2017-11-03 17:38 UTC

**Comment by lexoyo** [comment] 2019-04-18 16:42
this component is now live on preprod.silex.me for you to test please
