### ISSUE TITLE
Installation Issue With AppImage

### ISSUE THREAD

**Issue by Areahints** [silexlabs/Silex#880] opened 2019-02-01 20:05 UTC
Hello, I am trying to install Silex via appimage

i run 
`chmod a+x silex.appimage`
`./silex.appimage`
it displays this on the terminal

```
Silex starts with front end version [ '2', '2', '7' ]
/tmp/.mount_silex.0soM8b/resources/app.asar/node_modules

```
Its been at this point for over 6 hours now so I know its definitely not working,  what do I have to do to figure it out?

System Info

```
System information report, generated by Sysinfo: 2/1/2019 9:00:18 PM
http://sourceforge.net/projects/gsysinfo

SYSTEM INFORMATION
	Running Ubuntu Linux, the Ubuntu 18.04 (bionic) release.
	GNOME: 3.28.2 (Ubuntu)
	Kernel version: 4.15.0-45-lowlatency (#48-Ubuntu SMP PREEMPT Tue Jan 29 17:45:27 UTC 2019)
	GCC: 7 (x86_64-linux-gnu)
	Xorg: 1.19.6 (25 October 2018  04:11:27PM) (25 October 2018  04:11:27PM)
	Hostname: areahints-HP-15-Notebook-PC
	Uptime: 0 days 8 h 0 min

CPU INFORMATION
	GenuineIntel, Intel(R) Pentium(R) CPU  N3510  @ 1.99GHz
	Number of CPUs: 4
	CPU clock currently at 1981.806 MHz with 1024 KB cache
	Numbering: family(6) model(55) stepping(3)
	Bogomips: 3998.40
	Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer rdrand lahf_lm 3dnowprefetch epb pti tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm arat

MEMORY INFORMATION
	Total memory: 7865 MB
	Total swap: 979 MB

STORAGE INFORMATION
	SCSI device -  scsi0
		Vendor:  ATA      
		Model:  TOSHIBA MQ01ABF0 
	SCSI device -  scsi2
		Vendor:  Generic- 
		Model:  SD/MMC/MS PRO    

HARDWARE INFORMATION
MOTHERBOARD
	Host bridge
		Intel Corporation Atom Processor Z36xxx/Z37xxx Series SoC Transaction Register (rev 0a)
		Subsystem: Hewlett-Packard Company Atom Processor Z36xxx/Z37xxx Series SoC Transaction Register
	PCI bridge(s)
		Intel Corporation Atom Processor E3800 Series PCI Express Root Port 1 (rev 0a) (prog-if 00 [Normal decode])
		Intel Corporation Atom Processor E3800 Series PCI Express Root Port 3 (rev 0a) (prog-if 00 [Normal decode])
		Intel Corporation Atom Processor E3800 Series PCI Express Root Port 4 (rev 0a) (prog-if 00 [Normal decode])
		Intel Corporation Atom Processor E3800 Series PCI Express Root Port 1 (rev 0a) (prog-if 00 [Normal decode])
		Intel Corporation Atom Processor E3800 Series PCI Express Root Port 3 (rev 0a) (prog-if 00 [Normal decode])
		Intel Corporation Atom Processor E3800 Series PCI Express Root Port 4 (rev 0a) (prog-if 00 [Normal decode])
	ISA bridge
		Intel Corporation Atom Processor Z36xxx/Z37xxx Series Power Control Unit (rev 0a)
		Subsystem: Hewlett-Packard Company Atom Processor Z36xxx/Z37xxx Series Power Control Unit

GRAPHIC CARD
	VGA controller
		Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display (rev 0a) (prog-if 00 [VGA controller])
		Subsystem: Hewlett-Packard Company Atom Processor Z36xxx/Z37xxx Series Graphics & Display

SOUND CARD
	Multimedia controller
		Intel Corporation Atom Processor Z36xxx/Z37xxx Series High Definition Audio Controller (rev 0a)
		Subsystem: Hewlett-Packard Company Atom Processor Z36xxx/Z37xxx Series High Definition Audio Controller

NETWORK
	Network controller
		Ralink corp. RT3290 Wireless 802.11n 1T/1R PCIe
		Subsystem: Hewlett-Packard Company Ralink RT3290LE 802.11bgn 1x1 Wi-Fi and Bluetooth 4.0 Combo Adapter
	Ethernet controller
		Realtek Semiconductor Co., Ltd. RTL8101/2/6E PCI Express Fast/Gigabit Ethernet controller (rev 07)
		Subsystem: Hewlett-Packard Company RTL810xE PCI Express Fast Ethernet controller

```

**Comment by lexoyo** [comment] 2019-02-01 21:15
I never could make it work myself the appimage thing
Cc @jbIPS

**Comment by JbIPS** [comment] 2019-02-04 07:39
Hi! I'll check that today. While we're investigating you can use the .deb since you're on Ubuntu.

**Comment by JbIPS** [comment] 2019-02-04 08:39
You can find all the supported arch in the assets of the release.

Here's the deb: https://github.com/silexlabs/Silex/releases/download/v2.4.0/silex_2.4.0_amd64.deb

**Comment by Areahints** [comment] 2019-02-04 08:51
thanks so much!

**Comment by Areahints** [comment] 2019-02-04 14:44
@JbIPS so I installed the deb package and it was successful, however anytime I run silex, no GUI showed up! I can confirm that Silex is running because if I check my task manager, silex is there with a PID.

so I decided to start silex via terminal so I can see some output and this is what I got

```
Silex starts with backward compat version [ 2, 2, 8 ] and front end version [ 2, 8 ]
/opt/silex/resources/app.asar/node_modules
```

seems node is the problem...

is there a way to know all the node packages Silex depends on? maybe if I install them all before installing silex it will work?

**Comment by lexoyo** [comment] 2019-02-04 19:09
Silex requires node 8.10.0
https://github.com/silexlabs/Silex/blob/develop/.nvmrc

I don't know how to fix that in the build but maybe I should check the version of node when silex starts and echo a better warning? 

> seems node is the problem...

what makes you think that? you are probably right it is often the case with silex build but I wonder

**Comment by lexoyo** [comment] 2019-02-22 15:14
Hi 
Did you manage to get the desktop version to work?
CC @JbIPS

**Comment by Areahints** [comment] 2019-02-22 15:18
nope!

**Comment by 27aume** [comment] 2019-08-25 14:32
I am having the same issue on my Acer i5 - Ubuntu 18.04
Tested .deb and .AppImage

Just commenting to let you know its +1 occurrence on the issue.
Thank you, I'm tracking this issue in case a solution is found.

**Comment by lexoyo** [comment] 2019-08-25 16:24
cc @JbIPS

**Comment by canDry** [comment] 2020-05-06 20:19
Same issue as OP... tried executing appimage... nothing, nada, zip.  (ubun 18LTS w node V13.7)

**Comment by lexoyo** [comment] 2020-05-06 21:29
Hi
Can you try to install nodejs 10 (or 10.x.x) and do this commands please?

```
$ npm install -g silex-website-builder
$ silex-website-builder
```

To get node version 10 you can use nvm

**Comment by canDry** [comment] 2020-05-06 21:54
> Hi
> Can you try to install nodejs 10 (or 10.x.x) and do this commands please?
> 
> ```
> $ npm install -g silex-website-builder
> $ silex-website-builder
> ```
> 
> To get node version 10 you can use nvm

![Screenshot from 2020-05-06 17-50-40](https://user-images.githubusercontent.com/8286540/81232173-676f5b80-8fc2-11ea-983a-3d39ecc68e3b.jpg)
  
Thanks for the quick response Alex.  Used nvm to install/switch to v10.0.0  seems to be the same result.

**Comment by lexoyo** [comment] 2020-05-09 16:25
Ok I'm out of options then :(
Would you try with docker?
You have instructions in the readme

**Comment by lexoyo** [comment] 2020-05-10 20:59
I have reinstalled my OS and I was able to reproduce
I found the bug, this will be live soon
cc @JbIPS

**Comment by canDry** [comment] 2020-05-10 21:07
> I have reinstalled my OS and I was able to reproduce
> I found the bug, this will be live soon
> cc @JbIPS

Your dogged determination is impressive!  Thanks for digging into the problem.

**Comment by lexoyo** [comment] 2020-05-11 06:57
@JbIPS I merged into master and was expecting the release to be available as before as a draft but it never came... Do you know why?

**Comment by JbIPS** [comment] 2020-05-12 22:58
I see a draft for [2.5.61}(https://github.com/silexlabs/Silex/releases/tag/untagged-a1f9681fe932bd8eefe4) in the release panel. Isn't that the one?

**Comment by lexoyo** [comment] 2020-05-12 23:31
This was me, by Hans :(

**Comment by JbIPS** [comment] 2020-05-13 07:30
Thank you Hans 😁 !

Maybe the arrival of GitHub Actions stopped our workflow?

**Comment by lexoyo** [comment] 2020-05-13 12:26
Could you document here what you did? Was it in travis?
If you don't remember it's ok, I'll try to figure it out
Thx

**Comment by JbIPS** [comment] 2020-05-13 22:13
Yes, it was a Travis job, configured [here](https://github.com/silexlabs/Silex/blob/develop/.travis.yml)

**Comment by lexoyo** [comment] 2020-05-13 22:19
Ok thx

**Comment by lexoyo** [comment] 2020-05-26 15:38
YEAH
https://github.com/silexlabs/Silex/releases/tag/v2.5.61

Please someone test :sweat_smile:

**Comment by DurtyDev** [comment] 2020-05-26 16:20
I'm working on exe now. I'm thinking though the best way

**Comment by DurtyDev** [comment] 2020-05-30 17:06
For some reason Visual Studio Community 2019 is requiring that I build
everything step by step

**Comment by lexoyo** [comment] 2020-05-31 22:57
hey @DurtyDev yes i guess you have to follow all the steps
but i finally managed to create all the apps (windows, mac and linux) automatically
could you test these apps?
https://github.com/silexlabs/silex-desktop/releases

**Comment by DurtyDev** [comment] 2020-06-01 07:03
I was missing didn't have node or react installed. Congratulations. So you
have a working exe?

**Comment by lexoyo** [comment] 2020-06-01 09:28
I think so, but I only have tested the Linux app

Would you like to help and give the windows app a try ?

**Comment by canDry** [comment] 2020-06-07 04:56
Tried again, running the latest AppImage (using 10.0 and 14.4) and get this:
`> ./silex-desktop-2.6.0.AppImage

Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
`

**Comment by lexoyo** [comment] 2020-06-07 05:43
Hi
Yes I got this too which is why I wrote this in the docs

> downolad the .AppImage, make it executable and run it - you need libvips-dev installed (apt install libvips-dev or dnf install vips-devel)

Let me know if it works

I should probably add a test for this in the code and give a better error?

**Comment by canDry** [comment] 2020-06-07 07:05
> Hi Yes I got this too which is why I wrote this in the docs
> downolad the .AppImage, make it executable and run it - you need libvips-dev installed (apt install libvips-dev or dnf install vips-devel)
> Let me know if it works I should probably add a test for this in the code and give a better error?

Sorry about missing that bit.  
  
Just went to install and got this:  
  
```
After this operation, 257 MB of additional disk space will be used.
Do you want to continue? [Y/n]

```

**257MB of added stuff on my system... that's an 'N'.**

**Comment by lexoyo** [comment] 2020-06-07 18:01
Oh right :)
I'll see if I can get rid of this lib

**Comment by lexoyo** [comment] 2020-06-11 07:38
hey @canDry 
could you try [the v1.6.1 version](https://github.com/silexlabs/silex-desktop/releases/tag/v2.6.1) please? I added a check and do not crash if the vips-devel lib is not installed (I just disable the thumbnail in the file browser)

**Comment by lexoyo** [comment] 2020-10-28 18:54
Hello this is now fixed
If one has all the libs it takes to install sharp then Cloud Explorer will show the button to display images thumbnails

**Closed by lexoyo** 2020-10-28 18:54 UTC
Labels: bug
