### ISSUE TITLE
Issue: font family 

### ISSUE THREAD

**Issue by jotakar** [silexlabs/Silex#826] opened 2018-10-22 18:40 UTC
The font family select are empty in my last installation!!!
Embed fonts by hand appears, but not the default one, like in previous versions of silex.
And more about fonts:
When I load a template the embed fonts are not loaded so when we edit text his appearence change if it has a embeb font.
I cannot find the component that controls this. I supposes it's a propopotype component but I cannot find none
Please any help?

**Comment by lexoyo** [comment] 2018-10-23 12:21
i don't see what you mean, are you on localhost develop or master, or on editor.silex.me or preprod.silex.me?

**Comment by jotakar** [comment] 2018-10-23 14:13
I'm cloning from develop. It's the default branch (whats difference between this two branches?).
Previous versions doens't have this problem. 
I see that in September 21 there was a change in fonts manager. Now fon-family is a component and it isn't init with any value by popdotype. (see src/prodotype/text.yml ), then I suppose thar silex manage its values now. If I use old text.yml then the font-family list is ok, but fonts embed are not added.
Anyway when a template is loaded its fonts are not there (nor with last version nor with previous one). It's a deeper question I think.
I can't not find where or how silex update llist of font-family.
After that there are other task: how render the template looking for fonts, and then add to the fonts family list.

**Comment by jotakar** [comment] 2018-10-24 23:32
I've found a posible fix, but I don't like it very much.
I see that property.js contains a sentence 
silex.model.Property.prototype.fonts = []
If I init this property with default fonts family,  and modify in loadProperties to
this.fonts = styles['fonts'] ? this.fonts.concat(styles['fonts']) : this.fonts;

The fonts-family is not empty, but all fonts-family appear as embed fonts, so I dont like this method too much: default fonts are not embed fonts. I think It would be necessary more changes in other code.
 
And it works fine when load webpages, not for templates. 
With templates the family fonts used are not loaded so family-fonts show just the default fonts
I know templates has not the JSON with data about styles and fonts, as webpage has.
Any idea?
Thanks

**Comment by jotakar** [comment] 2018-10-25 11:33
Don't know if it's a good (and elegant) solution, but it looks like it works....
In property.js I've created a new property for **default fonts family** (array), then, when a page is loaded, this array is added to the embed fonts read from page and save into the actual fonts property.
The default fonts has not href property so I filter it in the fonts page of settins dialog.
When the page is to be saved,  it saves **just embedded fonts**, not the default (using a diff array operation)
It works with page created from templates, this is another problem to solve: extract embedded fonts from templates or modify templates and add a json fonts data
Will anybody ive an opinion about this idea?

**Comment by lexoyo** [comment] 2018-10-26 13:44
Oh ok
I think this is what I'm working on, update all templates with these fonts
I like it better to have no default fonts because they are heavy and sometimes it may be good to have no embed fonts
In order to have my work in progress on the templates, you can change package.json, replace `github:silexlabs/silex-templates#f9c2dcb` with `github:lexoyo/silex-templates#gh-pages` which is[ this repo](https://github.com/lexoyo/silex-templates?organization=lexoyo&organization=lexoyo)

**Comment by jotakar** [comment] 2018-10-26 14:28
Ok, thanks, I'll try it.
About default fonts, I'm not agree with you. There are several almost universal fonts family that are a minimal collection (you like arial, times. courier) present in any device and they don't need to be embed. It could be optional for every instance of Silex.
Bye.

**Comment by lexoyo** [comment] 2018-10-26 15:17
Yes you are right about these fonts, but the problem is that they are not displayed exactly the same by all browsers

They only differ by 1 or 2 pixels, but for silex websites it may break your site like this bug: #548

![64452b46-edf0-11e6-9a53-bbd5f14c4607](https://user-images.githubusercontent.com/715377/47575524-9410d480-d942-11e8-8740-05f6c1ce48cc.png)
![5485a492-edf0-11e6-869c-a417e4519123](https://user-images.githubusercontent.com/715377/47575527-9410d480-d942-11e8-96b3-58fca6a8c699.png)

So we need to embed the fonts in Silex templates to have the same site on all browsers

**Comment by lexoyo** [comment] 2018-11-12 12:07
hi @jotakar 
I am closing this issue, feel free to reopen it if you still have the problem

**Closed by lexoyo** 2018-11-12 12:07 UTC
