### ISSUE TITLE
Bug new version : resizing elements with border

### ISSUE THREAD

**Issue by antosilex** [silexlabs/Silex#502] opened 2016-10-17 15:27 UTC
It's way better but there is still a problem (even on preprod) when you try to reduce the element from the top right  corner, the element is moving.

**Comment by lexoyo** [comment] 2016-10-17 15:30
duplicate of #500

**Comment by lexoyo** [comment] 2016-10-17 18:32
I reopen it since the other issue is closed
I would not rate this bug as a priority, if someone wants to back it up please vote! or help me fix it

**Comment by lexoyo** [comment] 2017-05-15 19:14
fixed and live on editor.silex.me

**Closed by lexoyo** 2017-05-15 19:14 UTC
Labels: bug, help wanted
