### ISSUE TITLE
font problem

### ISSUE THREAD

**Issue by antosilex** [silexlabs/Silex#347] opened 2015-10-23 11:03 UTC
in the text box editor all the fonts are the same from "roboto condensed" until the end of the list

it would be nice to have a tutorial to add new fonts too

**Comment by lexoyo** [comment] 2015-10-24 22:19
Thank you, I'll have a look soon
I will probably remove these fonts

**Comment by antosilex** [comment] 2015-10-25 12:28
That is not what i ´ve asked ;)

**Comment by antosilex** [comment] 2015-11-02 14:11
is there a tutorial to add new fonts ?

**Comment by lexoyo** [comment] 2015-11-02 16:40
You can use this tutorial to learn how to get a font
http://knowledge.hubspot.com/articles/kcs_article/cos-general/how-do-i-add-google-fonts-to-my-new-landing-pages

Use the CSS editor to insert the code

And do not hesitate to make a tutorial here once you have understood how it works
https://github.com/silexlabs/Silex/wiki

**Comment by antosilex** [comment] 2015-11-02 16:50
ok to get it but i don't succeed to use it with silex

**Comment by lexoyo** [comment] 2015-11-02 17:25
you get the line with `@import`? you paste it in css editor
and then you use the font wit the other lines also in the css editor, e.g.
```
h1 {
   font-familly: ...
}
```

**Comment by lexoyo** [comment] 2015-11-23 23:31
I have found this 
https://github.com/silexlabs/Silex/issues/46

**Comment by singchan** [comment] 2016-08-17 15:33
duplicate of https://github.com/silexlabs/Silex/issues/347

**Closed by singchan** 2016-08-17 15:33 UTC
Labels: bug
